comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/09/01/Optimal-Taxation-of-Income-Generating-Choice/supp/18542_Data_and_Programs.zip
