comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/09/01/Monetary-Policy-Redistribution-and-Risk-Premia/supp/18014_Data_and_Programs.zip
