repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2023/03/01/Is-Attention-Produced-Optimally-Theory-and-Evidence-from-Experiments-with-Bandwidth-Enhancements/supp/20400_Data_and_Programs.zip
