comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2023/01/01/Nonparametric-Estimates-of-Demand-in-the-California-Health-Insurance-Exchange/supp/17215_Data_and_Programs.zip
