comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/11/01/Uneven-Growth-Automations-Impact-on-Income-and-Wealth-Inequality/supp/19417_Data_and_Programs.zip
