repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/09/01/Market-Size-and-Spatial-GrowthEvidence-From-Germanys-Post-War-Population-Expulsions/supp/18002_Data_and_Programs.zip
