comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/09/01/Gender-Differences-in-Peer-Recognition-by-Economists/supp/18027_Data_and_Programs.zip
