comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/03/01/global-banks-and-systemic-debt-crises/supp/17433_Data_and_Programs.zip
