comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/11/01/Achieving-Scale-Collectively/supp/18773_Data_and_Programs.zip
