comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/07/01/analytic-theory-monetary-shock/supp/17348_Data_and_Programs.zip
