comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/07/01/imitation-innovation-where-all-chinese-rd-going/supp/18586_Data_and_Programs.zip
