comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/07/01/maximum-likelihood-estimation-markov-regime-switching-models/supp/17249_Data_and_Programs.zip
