comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2023/01/01/Nexus-Tax-Laws-and-Economies-of-Density-in-E-Commerce-A-Study-of-Amazons-Fulfillment-Center-Network/supp/15265_Data_and_Programs.zip
