comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/03/01/optimal-taxation-and-rd-policies/supp/15445_Data_and_Programs.zip
