comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/07/01/effect-job-loss-and-unemployment-insurance-crime-brazil/supp/18984_Data_and_Programs.zip
