repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2023/03/01/Factions-in-Nondemocracies-Theory-and-Evidence-from-the-Chinese-Communist-Party/supp/19274_Data_and_Programs.zip
