repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2023/03/01/Connecting-to-Power-Political-Connections-Innovation-and-Firm-Dynamics/supp/18338_Data_and_Programs.zip
