comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/09/01/Tasks-Automation-and-the-Rise-in-US-Wage-Inequality/supp/19815_Data_and_Programs.zip
