comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/03/01/are-medical-care-prices-still-declining-re-examination-based/supp/17635_Data_and_Programs.zip
