comment: Re-run after bugfix in repboxStata.
repo_type: zip_url
url: https://www.econometricsociety.org/publications/econometrica/2022/07/01/terrorism-financing-recruitment-and-attacks/supp/18530_Data_and_Programs.zip
